stages:
  - build
  - sand-box

build:
  stage: build
  image: node:latest
  script:
    - npm install
  cache:
    paths:
      - node_modules/
  only:
    - lektur-try-deploy

staging:
  stage: sand-box
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=lektur-app --api-key=$LEKTUR_API_KEY
  only:
    - lektur-try-deploy
