export const GET_QUESTIONS = "GET_QUESTIONS";
export const POST_QUESTIONS = "POST_QUESTIONS";
export const GET_QUESTIONS_TEMP = "GET_QUESTIONS_TEMP";
export const PUT_FINAL_SCORE = "PUT_FINAL_SCORE";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
