export const GET_QUESTIONS = "GET_QUESTIONS";
export const POST_QUESTIONS = "POST_QUESTIONS";
export const GET_ONE_QUESTION = "GET_ONE_QUESTION";
export const PUT_FINAL_SCORE = "PUT_FINAL_SCORE";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
