export const GET_ALL_COURSES = 'GET_ALL_COURSES'
export const GET_COURSE_DETAIL = 'GET_COURSE_DETAIL'
export const GET_COURSE_STUDENT = 'GET_COURSE_STUDENT'
export const POST_ENROLL_COURSE = 'POST_ENROLL_COURSE'
