export const GET_PROFILE_TEACHER = "GET_PROFILE_TEACHER";
export const CREATE_COURSE = "CREATE_COURSE";
export const STUDENTS_ACCEPT = "STUDENT_ACCEPT";
export const STUDENT_APPROVE = "STUDENT_APPROVE";
export const STUDENT_INVITE = "STUDENT_INVITE";
